openapi: 3.0.3
info:
  title: only_one_backend
  description: |-
    「どみとる」のバックエンドシステムであるFlaskベースのWebAPIです。
  license:
    name: Flask 3.0.x
    url: https://msiz07-flask-docs-ja.readthedocs.io/ja/latest/license.html
  version: 3.0.0
servers:
  - url: https://your_host
    description: Production Server
  - url: http://localhost:5000
    description: Executing with uWSGI
  - url: http://localhost:5500
    description: Deveropment Server
tags:
  - name: iot
    description: IoTデバイスがアクセスするAPI
  - name: api
    description: フロントエンドが使用するAPI
paths:
  /iot/insert:
    post:
      tags:
        - iot
      summary: データの登録
      description: JSONデータや画像データを元にデータベースへ使用状況データを登録します。このAPIへのアクセスはデータベースに登録されたIPを持つIoTデバイスに限られます。
      deprecated: false
      requestBody:
        required: true
        description: 対象となる機器(洗濯機や乾燥機、シャワー室など)に割り振られたIDをkey、データベースへ登録する値をvalueとする。ここでは使用可能状態を1、使用不可を0としている。また、`image/jpeg`を送る際はIDは送信してきたIPから推測し、valueは画像を元に判断される。
        content:
          application/json:
            schema:
              type: object
              properties:
                DR_311:
                  type: integer
                  format: int8
                  example: 1
                  description: IoTID as key, status (0 or 1) as value
                DR_312:
                  type: integer
                  format: int8
                  example: 0
          image/jpeg:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        '400':
          description: Invalid request supplied
        '403':
          description: Unauthorized IP
    
  /api/dashboard:
    get:
      tags:
        - api
      summary: 利用状況データの取得
      description: 最新の利用状況データを返します。データがデータベースへ登録されていない場合はnull、もしくはそのデータ項目が欠落します。現在、`/api/dashbord_details`がより詳細な情報を返すため、非推奨としています。
      deprecated: true
      parameters:
        - name: dormitory
          in: query
          description: Name of the dormitory building to get. If this parameter is ALL or not using, get all data of domitory.
          schema:
            type: string
            example: MOU, CEN, SEA, SPA or ALL
        - name: floor
          in: query
          description: The building floor to get. This parameter is ignored if the dormitory parameter is ALL or not specified. If this parameter is ALL or not using, get all data of floor.
          schema:
            type: string
            example: 1 ~ 5 or ALL
        - name: type
          in: query
          description: Name of the data item to get. If this parameter is PB, other parameter is ignored. If this parameter is ALL or not using, get all data items.
          schema:
            type: string
            example: DR, WA, SW, PB or ALL
        - name: timeExclusion
          in: query
          description: If sending true in this parameter, It will return NULL for any items whose data has not been updated for a certain period of time. This parameter allows you to filter out data that is too old and not in keeping with the current situation.
          schema:
            type: string
            example: true
            
      responses:
        '200':
          description: Successful operation. If a parameter is specified, only the specified items are returned. Also, if the target item does not exist (e.g. dormitory=MOU&floor=4), an empty element is returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessDashboard'
        
        '400':
          description: Invalid query parameters.

  /api/dashboard_details:
    get:
      tags:
        - api
      summary: 利用状況の詳細を取得
      description: 利用状況の詳細なデータを取得します。データベースにデータが登録されていない場合はstatus, startedTime, lastDataTimeはnullを返します。startedTimeは利用不可になった時点の時間を表します。lastDataTimeはデータが登録された時間を表します。statusは状態を表します。trueなら利用可能を表します。
      deprecated: false
      parameters:
        - name: id
          in: query
          description: IoTデバイスに割り振られたIDを指定します。
          schema:
            type: string
            example: WA_311
        - name: dormitory
          in: query
          description: 寮棟を指定します。ALLが指定された場合やパラメータが存在しない場合はすべてのデータを返します。
          schema:
            type: string
            example: ALL
        - name: floor
          in: query
          description: 階層を指定します。ALLが指定された場合やパラメータが存在しない場合はすべてのデータを返します。
          schema:
            type: string
            example: 1 ~ 5 or ALL
        - name: type
          in: query
          description: IoTデバイスの分類を指定します。
          schema:
            type: string
            example: DR, WA, SW, PB or ALL
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessDashboardDetailed'
        
        '400':
          description: Invalid query parameters.

  /api/transitions:
    get:
      tags:
        - api
      summary: 利用状況の推移の取得
      description: 利用状況の推移を取得します。集計期間中にデータベースに値が登録されていない場合、前後の値を通る直線上の値を返します。前後に値がない場合は0を返します。
      deprecated: false
      parameters:
        - name: id
          in: query
          description: IoTデバイスに割り振られたIDを指定します。
          schema:
            type: string
            example: WA_311
        - name: dormitory
          in: query
          description: 寮棟を指定します。ALLが指定された場合やパラメータが存在しない場合はすべてのデータを返します。
          schema:
            type: string
            example: ALL
        - name: floor
          in: query
          description: 階層を指定します。ALLが指定された場合やパラメータが存在しない場合はすべてのデータを返します。
          schema:
            type: string
            example: 1 ~ 5 or ALL
        - name: type
          in: query
          description: IoTデバイスの分類を指定します。
          schema:
            type: string
            example: DR, WA, SW, PB or ALL
        - name: weekday
          in: query
          description: 曜日を指定します。
          schema:
            type: string
            example: MON, MONDAY, TUE, TUESDAY and so on.
        - name: weekly
          in: query
          description: 集計の範囲を直近の1週間としたデータ項目を取得します。
          schema:
            type: string
            example: TRUE
        - name: monthly
          in: query
          description: 集計の範囲を直近の1ヶ月としたデータ項目を取得します。
          schema:
            type: string
            example: TRUE
        - name: halfYear
          in: query
          description: 集計の範囲を直近の半年間としたデータ項目を取得します。
          schema:
            type: string
            example: TRUE
        - name: startTime
          in: query
          description: 集計期間の開始日時を指定します。
          schema:
            type: string
            example: YYYY-MM-DD-hh:mm:ss
        - name: endTime
          in: query
          description: 集計期間の終了日時を指定します。startTimeが指定されない場合、HTTP 400を返します。startTimeのみが存在する場合、endTimeは現在時刻(NOWを指定した場合と同じ)となります。
          schema:
            type: string
            example: YYYY-MM-DD-hh:mm:ss or NOW
        - name: groupByDormitory
          in: query
          description: 寮棟でグループ化して集計します。
          schema:
            type: string
            example: TRUE
        - name: groupByFloor
          in: query
          description: 寮棟および階層でグループ化して集計します
          schema:
            type: string
            example: TRUE
        - name: groupByID
          in: query
          description: IoTデバイスごとに集計します。
          schema:
            type: string
            example: TRUE
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessTransitions'
        
        '400':
          description: Invalid query parameters.
  
  
components:
  schemas:
    Success:
      type: object
      properties:
        status:
          type: string
          example: success
        data:
          type: array
          items:
            type: object
            properties:
              ID:
                type: string
                example: IoTID
              status:
                type: integer
                example: 1
    SuccessDashboard:
      type: object
      properties:
        MOU:
          type: object
          properties:
            F1:
              type: object
              properties:
                DR:
                  type: array
                  items:
                    type: boolean
                WA:
                  type: array
                  items:
                    type: boolean
            F2:
              type: object
              properties:
                DR:
                  type: array
                  items:
                    type: boolean
                WA:
                  type: array
                  items:
                    type: boolean
            F3:
              type: object
              properties:
                DR:
                  type: array
                  items:
                    type: boolean
                WA:
                  type: array
                  items:
                    type: boolean
            SW:
              type: array
              items:
                type: boolean
        CEN:
          type: object
          properties:
            F1:
              type: object
              properties:
                DR:
                  type: array
                  items:
                    type: boolean
                WA:
                  type: array
                  items:
                    type: boolean
            F2:
              type: object
              properties:
                DR:
                  type: array
                  items:
                    type: boolean
                WA:
                  type: array
                  items:
                    type: boolean
            F3:
              type: object
              properties:
                DR:
                  type: array
                  items:
                    type: boolean
                WA:
                  type: array
                  items:
                    type: boolean
            SW:
              type: array
              items:
                type: boolean
        SEA:
          type: object
          properties:
            F1:
              type: object
              properties:
                DR:
                  type: array
                  items:
                    type: boolean
                WA:
                  type: array
                  items:
                    type: boolean
            F2:
              type: object
              properties:
                DR:
                  type: array
                  items:
                    type: boolean
                WA:
                  type: array
                  items:
                    type: boolean
            F3:
              type: object
              properties:
                DR:
                  type: array
                  items:
                    type: boolean
                WA:
                  type: array
                  items:
                    type: boolean
            SW:
              type: array
              items:
                type: boolean
        SPA:
          type: object
          properties:
            F1:
              type: object
              properties:
                DR:
                  type: array
                  items:
                    type: boolean
                WA:
                  type: array
                  items:
                    type: boolean
            F2:
              type: object
              properties:
                DR:
                  type: array
                  items:
                    type: boolean
                WA:
                  type: array
                  items:
                    type: boolean
            F3:
              type: object
              properties:
                DR:
                  type: array
                  items:
                    type: boolean
                WA:
                  type: array
                  items:
                    type: boolean
            F4:
              type: object
              properties:
                DR:
                  type: array
                  items:
                    type: boolean
                WA:
                  type: array
                  items:
                    type: boolean
            F5:
              type: object
              properties:
                DR:
                  type: array
                  items:
                    type: boolean
                WA:
                  type: array
                  items:
                    type: boolean
            SW:
              type: array
              items:
                type: boolean
        PB:
          type: array
          items:
            type: integer
    SuccessDashboardDetailed:
      type: array
      items:
        type: object
        properties:
          dormitory:
            type: string
            example: MOU, CEN, SEA, SPA or ALL
          floor:
            type: integer
            example: 1 ~ 5
          No:
            type: integer
            example: 1 ~ 4
          startedTime:
            type: string
            example: YYYY-MM-DD hh:mm:ss
          lastDataTime:
            type: string
            example: YYYY-MM-DD hh:mm:ss
          status:
            type: integer
            example: boolean or integer
          type:
            type: string
            example: DR, WA, SW, PB or ALL
    SuccessTransitions:
      type: array
      items:
        type: object
        properties:
          type:
            type: string
            example: DR, WA, SW, PB or ALL
          dormitory:
            type: string
            example: MOU, CEN, SEA, SPA or ALL
          floor:
            type: integer
            example: 1 ~ 5
          No:
            type: integer
            example: 1 ~ 4
          data:
            type: object
            properties:
              labels:
                type: array
                items:
                  type: string
                  example: hh:mm:ss
              datasets:
                type: array
                items:
                  type: object
                  properties:
                    label:
                      type: string
                      example: 一週間
                    data:
                      type: array
                      items:
                        type: number
                        example: 3.1
