SET GLOBAL event_scheduler = ON;

/* CREATE EVENT cleaning_delete ON SCHEDULE EVERY 1 MONTH DO DELETE FROM `cleaing` AS T WHERE DATE_FORMAT(CONCAT(T.year_month, '-', LPAD(CONVERT(T.day, CHAR(2)), 2, '0')), '%Y-%m-%d') < DATE_SUB(CURDATE(), INTERVAL 6 MONTH); */
/* CREATE EVENT rollCall_delete ON SCHEDULE EVERY 1 MONTH DO DELETE FROM `rollCall` AS T WHERE T.registeredTime < DATE_SUB(CURDATE(), INTERVAL 6 MONTH); */
CREATE EVENT IoT_Data_delete ON SCHEDULE EVERY 1 MONTH DO DELETE FROM `IoTData` AS T WHERE T.time < DATE_SUB(CURDATE(), INTERVAL 6 MONTH);

